### ISSUE TITLE
akka.actor.UnstartedCell cannot be cast to akka.actor.ActorCell

### ISSUE THREAD

**Issue by TimothyBergstrom** [statisticalbiotechnology/quandenser-pipeline#3]
Dinosaur bug:

Sometimes, when running thousands of files with the parallel function of quandenser-pipeline, dinosaur crashes due to akka.actor error. This does makes the std::system in quandenser never finish, thus making nextflow wait for a process indefinitely. This problem is within dinosaur, but is actually stems from akka actors.

Error output of a test:

```
Quandenser version 0.01.0, Build Date Mar  5 2019 13:22:04
Copyright (c) 2015-17 Matthew The. All rights reserved.
Written by Matthew The (matthew.the@scilifelab.se) in the
School of Biotechnology at the Royal Institute of Technology in Stockholm.
Issued command:
quandenser-modified --batch modified_list.txt --max-missing 99 --parallel-1 true --dinosaur-threads 20
Started Wed Mar  6 15:46:37 2019

Processing "20150907_QEp1_LC7_PhGe_SA_Plate2D_47_2.mzML" with Dinosaur.
java -Xmx24000M -jar /usr/share/java/Dinosaur-1.1.3.free.jar --force --concurrency=20 --profiling=true --nReport=0 --outDir=Quandenser_output/dinosaur /media/storage/ptruong/20150907_QEp1_LC7_PhGe_SA_Plate2D_47_2.mzML
Dinosaur 1.1.3    built:${maven.build.timestamp}
  mzML file: /media/storage/ptruong/20150907_QEp1_LC7_PhGe_SA_Plate2D_47_2.mzML
    out dir: Quandenser_output/dinosaur
   out name: 20150907_QEp1_LC7_PhGe_SA_Plate2D_47_2

Exception in thread "main" java.lang.ClassCastException: akka.actor.UnstartedCell cannot be cast to akka.actor.ActorCell
	at akka.actor.ActorDSL$Extension.mkChild(ActorDSL.scala:106)
	at akka.actor.dsl.Inbox$InboxExtension$class.newReceiver(Inbox.scala:55)
	at akka.actor.ActorDSL$Extension.newReceiver(ActorDSL.scala:89)
	at akka.actor.dsl.Inbox$Inbox.<init>(Inbox.scala:169)
	at akka.actor.dsl.Inbox$class.inbox(Inbox.scala:165)
	at akka.actor.ActorDSL$.inbox(ActorDSL.scala:75)
	at akka.actor.Inbox$.create(ActorDSL.scala:151)
	at se.lth.immun.FeatureFinder.<init>(FeatureFinder.scala:37)
	at se.lth.immun.Dinosaur$.main(Dinosaur.scala:60)
	at se.lth.immun.Dinosaur.main(Dinosaur.scala)
```

**Comment by TimothyBergstrom** [comment]
Another crash:
```

java.lang.NumberFormatException: For input string: "-nan"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at scala.collection.immutable.StringLike$class.toDouble(StringLike.scala:232)
	at scala.collection.immutable.StringOps.toDouble(StringOps.scala:31)
	at se.lth.immun.TargetFile$$anonfun$parse$1.apply(TargetFile.scala:89)
	at se.lth.immun.TargetFile$$anonfun$parse$1.apply(TargetFile.scala:71)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at se.lth.immun.TargetFile.parse(TargetFile.scala:71)
	at se.lth.immun.TargetFile.read(TargetFile.scala:50)
	at se.lth.immun.TargetFile.read(TargetFile.scala:34)
	at se.lth.immun.Dinosaur$.main(Dinosaur.scala:55)
	at se.lth.immun.Dinosaur.main(Dinosaur.scala)
.                              .
```

**Comment by TimothyBergstrom** [comment]
Update:

This issue cannot be fixed without changing Dinosaur in Quandenser. Due to the "random" nature of actors, this issue might be impossible to fix. Perhaps adding some function in the pipeline to "restart" failed processes would work. 

The ["errorStrategy"](https://www.nextflow.io/docs/latest/process.html) parameter with "maxRetries" set as 1 could be useful for this purpose

**Comment by TimothyBergstrom** [comment]
Fixed in with file [command_wrapper.py](https://github.com/statisticalbiotechnology/quandenser-pipeline/blob/master/dependencies/command_wrapper.py) and commit https://github.com/statisticalbiotechnology/quandenser-pipeline/commit/46ee2647a81d019c1665df1db0555ac52363b795

I have not seen this error happening anymore when using the script, so it has been difficult to test exactly how it behaves (maybe 1 in 1000 files will make this error). I have made some simple tests, and it seem to work at least.

**Comment by TimothyBergstrom** [comment]
Note: This addition has proven to fix the issue on both quandenser_parallel_1 AND quandenser_parallel_3, which is kind of neat. This has yielded a lot more stability on the pipeline. Even if the bugs were to be fixed, the command wrapper would impact the processing time minimally

**Comment by MatthewThe** [comment]
This Dinosaur crash is still present when running thousands of files. It doesn't kill the pipeline thanks to the maxRetries = 1 setting, but it would be good to solve this at some point.
